---
app:
  image:
    tag: "4.6.1-app"
assets:
  image:
    tag: "4.6.1-assets"
storage:
  cephfs:
    volumes:
      locales:
        path: "/volumes/_nogroup/275e9568-3429-4abb-883e-835212586b7b"
      uploads:
        path: "/volumes/_nogroup/506e3c86-a134-4ad2-bff6-1247a5a717e0"
